/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 meti_rigged.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/meti_rigged.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0.203, 0.211, 0.014]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.spine} />
        <primitive object={nodes.Bone003} />
        <primitive object={nodes.HipsR} />
        <primitive object={nodes.HipsL} />
        <skinnedMesh geometry={nodes['tripo_node_1b1ddeee-ec11-47c4-83d8-39f001f58053'].geometry} material={materials['tripo_material_1b1ddeee-ec11-47c4-83d8-39f001f58053']} skeleton={nodes['tripo_node_1b1ddeee-ec11-47c4-83d8-39f001f58053'].skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/meti_rigged.glb')
